In [1]:
from sklearn.model_selection import train_test_split

from tools import *

In [2]:
radius = 8
ban_el = 1
seed = 0
bins = 1024

In [3]:
db = preprocessing('pahdb.ascii')
db.shape[0]

4233

In [4]:
# get_xyz_file(db, 'db_xyz')
# get_mol_file('db_xyz', 'db_mol')

In [5]:
fp = get_fingerprint('db_mol', radius=radius)
for i in db:
    i['fingerprint'] = fp[i['uid']]

db[961]['spectrum'] = np.delete(db[961]['spectrum'], -1, axis=0)  # 异常值处理
db = banning(db, ban_el=ban_el)

db.shape[0]

4007

In [6]:
%%time

db_train, db_test = train_test_split(db, test_size=0.2, random_state=seed)

fp_train, fp_test = get_onehot_fingerprint(db_train, db_test)
print(fp_train)

spec_train, spec_test = get_binned_spectrum(db_train, db_test, bins=bins)

SparseTensor(indices=tf.Tensor(
[[    0   408]
 [    0  1405]
 [    0  1553]
 ...
 [ 3204 56305]
 [ 3204 56621]
 [ 3204 57116]], shape=(389306, 2), dtype=int64), values=tf.Tensor([1 1 1 ... 1 1 1], shape=(389306,), dtype=int32), dense_shape=tf.Tensor([ 3205 57282], shape=(2,), dtype=int64))
Wall time: 3min 34s


In [7]:
np.savez(f'dataset/{radius}_{ban_el}_{seed}_{bins}',
         pahdb=[db_train, db_test], fingerprint=[fp_train, fp_test], spectrum=[spec_train, spec_test])

D:\anaconda3\lib\site-packages\numpy\lib\npyio.py:719: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  val = np.asanyarray(val)
